baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 't0x1n'
theme = 'hugo-coder'

# Enable syntax highlighting for code blocks
pygmentsStyle = 'github-dark'
pygmentsUseClasses = true

[params]
  author = "Sumukh Chitloor"
  # Change info to a single string instead of an array
  info = "Welcome to my realm. This is where I document security research, share automation hacks, and occasionally rant about the state of modern tech."
  description = "Sumukh's personal website - Security Engineer building secure fintech solutions"
  keywords = "security engineer, penetration testing, red team, CTF, cybersecurity, fintech security, DPDPA compliance"
  
   # Your avatar/profile image
  avatarURL = "images/avatar.jpeg"
 
  
  # Enable additional features
  enableTwemoji = true
  colorScheme = "dark"
  hideColorSchemeToggle = false
  
  # Enable custom CSS
  customCSS = ["css/custom.css"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/sumukhchitloor"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://in.linkedin.com/in/sumukh-chitloor"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/sumukhchitloor"

# Main navigation menu
[[menu.main]]
  name = "about"
  weight = 1
  url = "/about/"

[[menu.main]]
  name = "security research"
  weight = 3
  url = "/research/"

[[menu.main]]
  name = "blogs"
  weight = 2
  url = "/posts/"